---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  # ------------------ BASE ------------------
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-shebang-scripts-are-executable
      - id: check-toml
      - id: detect-private-key
      - id: fix-byte-order-marker
      - id: mixed-line-ending
  - repo: https://github.com/jumanjihouse/pre-commit-hook-yamlfmt
    rev: 0.2.2
    hooks:
      - id: yamlfmt
        args: [--mapping, "2", --sequence, "4", --offset, "2", --width, "150", --preserve-quotes]
        exclude: ^.github/dependabot.yml
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.32.0
    hooks:
      - id: markdownlint
        args: [--ignore, node_modules, --ignore, src, --fix, --disable, MD013]
  # ------------------ PYTHON ------------------
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.6.0
    hooks:
      - id: reorder-python-imports
  - repo: https://github.com/charliermarsh/ruff-pre-commit
      # Ruff version.
    rev: "v0.0.245"
    hooks:
      - id: ruff
        args: ["--fix", "--ignore=E402,E501,E722"]
