---
version: "3.8"

services:
  scrapyd:
    build: ./
    container_name: twelve-data-scrape
    environment:
      - TZ=${TZ}
    ports:
      - ${PORT}:6800
    volumes:
      - ${INPUT_PATH}:/app/inputs
      - ${OUTPUT_PATH}:/app/outputs
      - ${LOG_PATH}:/app/logs
    restart: unless-stopped
